"""empty message

Revision ID: dc66854eaa2a
Revises: ffdc0a98111c
Create Date: 2021-10-20 13:30:49.198692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc66854eaa2a'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'photo')
    # ### end Alembic commands ###
