"""empty message

Revision ID: a8f3b8ed8453
Revises: 8e2bcf7173a0
Create Date: 2021-10-20 13:48:00.061030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f3b8ed8453'
down_revision = '8e2bcf7173a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('media_1', sa.String(), nullable=True),
    sa.Column('media_2', sa.String(), nullable=True),
    sa.Column('media_3', sa.String(), nullable=True),
    sa.Column('media_4', sa.String(), nullable=True),
    sa.Column('media_5', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
